@startuml 会議室予約システムドメインモデル図
skinparam componentStyle rectangle

' ユーザー
' ユーザーID、ユーザー名
[ユーザー] o-- [ユーザーID]
[ユーザー] o-- [ユーザー名]

' 会議室
' 会議室名
[会議室] o-- [会議室名]

' 予約
' 予約番号、会議開始終了時刻、会議の目的
[予約番号] o-- [予約]
[予約] o-- [予約番号]
[予約] o-- [会議開始終了時刻]
[予約] o-- [会議の目的]

@enduml