@startuml ECommerceAdminDomainModel
skinparam componentStyle rectangle

' メインのシステム
[管理システム] o-- [顧客管理]
[管理システム] o-- [商品管理]
[管理システム] o-- [注文管理]
[管理システム] o-- [配送状況管理]
[管理システム] o-- [返金・返品管理]
' 管理システムいらないかもシステムは全体像としての扱いだから管理でいいかも



[顧客管理] o-- [ユーザーID]
[顧客管理] o-- [名前]
[顧客管理] o-- [住所]
[顧客管理] o-- [電話番号]
[顧客管理] o-- [メールアドレス]
[顧客管理] o-- [パスワード]


[商品管理] o-- [商品番号]
[商品管理] o-- [商品名]
[商品管理] o-- [価格]
[商品管理] o-- [在庫数]


[注文管理] o-- [注文番号]
[注文管理] o-- [注文日]
[注文管理] o-- [数量]
[注文管理] o-- [合計金額]


[配送状況管理] o-- [注文番号]
[配送状況管理] o-- [配達業者ID]

[返金・返品管理] o-- [注文番号]
[返金・返品管理] o-- [返金金額]
[返金・返品管理] o-- [クレジットカード情報]

