@startuml 注文管理システム
skinparam componentStyle rectangle
[顧客] o-- [ユーザーID]
[顧客] o-- [名前]
[顧客] o-- [電話番号]
[顧客] o-- [メールアドレス]
[顧客] o-- [住所]
'[ユーザー] o-- [支払情報]
[顧客] --o [カート]
'[クレジットカード] o-- [カード番号]
'[クレジットカード] o-- [セキュリティコード]
'[カート] o-- [ユーザーID]
[カート] o-- [商品]
'[カート] o-- [商品ID]
[カート] o-- [数量]
'[カート] o-- [商品の小計]
'[カート] o-- [注文ID]
'[支払情報] o-- [支払ID]
'[支払情報] o-- [支払日時]
'[支払情報] o-- [支払金額]
[配送] o-- [注文]
[配送] o-- [住所]
[配送] o-- [配送日時]
[配送] o-- [配送先名]
[配送] o-- [配送時間帯]
'[配送] o-- [配送状況]
'[配送状況] <|-- [配達中]
'[配送状況] <|-- [配達完了]
'[配送状況] <|-- [不在のため配達できません]


[管理者] o-- [名前]
[管理者] o-- [管理者ID]
[管理者] o-- [種別]
'[管理者] o-- [注文履歴]
[種別] <|-- [マスター]
[種別] <|-- [倉庫管理者]
[種別] <|-- [カスタマーサポート]

[決済ログ] o-- [決済ID]
[決済ログ] o-- [注文ID]
[決済ログ] o-- [ユーザーID]
[決済ログ] o-- [決済金額]
[決済ログ] o-- [決済日時]
[決済ログ] o-- [結果]
[結果] <|-- [成功] 
[結果] <|-- [失敗]

[商品] o-- [商品名]
[商品] o-- [商品ID]
'[商品] o-- [商品の詳細]
[商品] o-- [値段]
[商品] o-- [在庫数]
'[商品の詳細] <|--
[注文] o-- [注文ID]
[注文] o-- [ユーザーID]
[注文] o-- [注文日時]
[注文] o-- [合計金額]
[注文] o-- [注文詳細]
[注文] o-- [入金状況]
[入金状況] <|-- [入金済み]
[入金状況] <|-- [その他]
[注文詳細] o-- [商品]
[注文詳細] o-- [個数]
[注文詳細] o-- [小計]
'[注文詳細] o-- [返品]
'[注文] o-- [クレジットカード]
[注文] o-- [出荷状況]
[出荷状況] <|-- [出荷準備中]
[出荷状況] <|-- [出荷待ち]
[出荷状況] <|-- [出荷済み]
[出荷状況] <|-- [キャンセル]
[出荷状況] <|-- [差し戻し(不在など)]
'[注文履歴] o-- [商品ID]
'[注文履歴] o-- [注文ID]
'[注文履歴] o-- [注文日時]
'[注文履歴] o-- [決済金額]

[返品] o-- [返品ID]
[返品] o-- [注文詳細]
'[返品] o-- [商品名]
'[返品] o-- [注文]
[返品] o-- [返品理由]
[販売者都合] <|-- [商品の破損]
[購入者都合] <|-- [商品が気に入らなかった]
[返品理由] <|-- [販売者都合]
[返品理由] <|-- [購入者都合]
'[返品] o-- [商品の状態]
[返品] o-- [返品日時]
[返品] o-- [返品状況]
[返品状況] <|-- [発送待ち]
[返品状況] <|-- [発送中]
[返品状況] <|-- [到着済み]
'[返品] o-- [返金]
'[返品] o-- [返金ID]
[返品] o-- [返金日時]
[返品] o-- [返金金額]
'
@enduml