@startuml 訪問者システムドメインモデル図
skinparam componentStyle rectangle
[Webページ] o-- [ユーザー]

[ユーザー] o-- [ユーザーID]
[ユーザー] o-- [パスワード]
[ユーザー] o-- [名前]
[ユーザー] o-- [学校名]
[ユーザー] o-- [所属名]
[ユーザー] o-- [メールアドレス]
[ユーザー] o-- [電話番号]
[ユーザー] o-- [年齢]


@enduml