@startuml 訪問者システムクラス図
skinparam classAttributeIconSize 0

class Webページ

class ユーザー {
  -ユーザID
  -パスワード
  -名前
  -学校名
  -所属名
  -メールアドレス
  -電話番号
  -年齢
  +登録()
  +参照()
  +情報変更()
  +削除()
  +他の訪問者情報参照()
  +ログイン・ログアウト()

}

Webページ "1" o-- "0..*" ユーザー

@enduml