@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName: Storing
'  myTimeはDateTimeかも bigint?=UNIXTime
' UNIXTimeとは 1900/01/01 00:00:00 を0として、1ずつ追加する
 -myTime: int
 -goodMorning: Storing
 -goodAfternoon: Storing
 -goodNight: Storing
 -firstValue: int
 -secondValue: int
'  教科書にない
 -result: int

' 返り値: void 何も値を返さない
 +getMyName(): Storing
 +setMyName(): int
'  +時刻の設定()
 +setNewTime(): void
'  +時刻に応じた挨拶の言葉を取得()
 +getMyGreeting(): Storing
'  +2つの整数を設定()
' 教科書にない
 +setTwoValues(): void
'  +足し算結果登録()
'  +足し算結果取得()
 +setAndGetResult(): int
}

@enduml
